version: '3.8'

services:
  viethiphop-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viethiphop-be
    restart: always
    ports:
      - "3010:3000"
    env_file:
      - .env.production
